const UserTopItems = {
  items: [
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
            },
            href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
            id: "04gDigrS5kc9YWfZHwBETP",
            name: "Maroon 5",
            type: "artist",
            uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1pCA38N6MkLlthXtAOvZTU",
        },
        href: "https://api.spotify.com/v1/albums/1pCA38N6MkLlthXtAOvZTU",
        id: "1pCA38N6MkLlthXtAOvZTU",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27386a8ab515de4b7aef28cd631",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0286a8ab515de4b7aef28cd631",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485186a8ab515de4b7aef28cd631",
            width: 64,
          },
        ],
        name: "JORDI (Deluxe)",
        release_date: "2021-06-11",
        release_date_precision: "day",
        total_tracks: 14,
        type: "album",
        uri: "spotify:album:1pCA38N6MkLlthXtAOvZTU",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
          },
          href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
          id: "04gDigrS5kc9YWfZHwBETP",
          name: "Maroon 5",
          type: "artist",
          uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 189486,
      explicit: false,
      external_ids: {
        isrc: "USUM71913350",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/4cktbXiXOapiLBMprHFErI",
      },
      href: "https://api.spotify.com/v1/tracks/4cktbXiXOapiLBMprHFErI",
      id: "4cktbXiXOapiLBMprHFErI",
      is_local: false,
      name: "Memories",
      popularity: 89,
      preview_url: null,
      track_number: 11,
      type: "track",
      uri: "spotify:track:4cktbXiXOapiLBMprHFErI",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
            },
            href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
            id: "04gDigrS5kc9YWfZHwBETP",
            name: "Maroon 5",
            type: "artist",
            uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
          },
        ],
        available_markets: [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IL",
          "IN",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6ijGiBcBfUwkoyHn5VUHU2",
        },
        href: "https://api.spotify.com/v1/albums/6ijGiBcBfUwkoyHn5VUHU2",
        id: "6ijGiBcBfUwkoyHn5VUHU2",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273fc8633e22a7dba6aab817bff",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02fc8633e22a7dba6aab817bff",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851fc8633e22a7dba6aab817bff",
            width: 64,
          },
        ],
        name: "Overexposed Track By Track",
        release_date: "2012-01-01",
        release_date_precision: "day",
        total_tracks: 33,
        type: "album",
        uri: "spotify:album:6ijGiBcBfUwkoyHn5VUHU2",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
          },
          href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
          id: "04gDigrS5kc9YWfZHwBETP",
          name: "Maroon 5",
          type: "artist",
          uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop",
          },
          href: "https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop",
          id: "137W8MRPWKqSmrBGDBFSop",
          name: "Wiz Khalifa",
          type: "artist",
          uri: "spotify:artist:137W8MRPWKqSmrBGDBFSop",
        },
      ],
      available_markets: [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IL",
        "IN",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "RO",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 231173,
      explicit: true,
      external_ids: {
        isrc: "USUM71203347",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1XGmzt0PVuFgQYYnV2It7A",
      },
      href: "https://api.spotify.com/v1/tracks/1XGmzt0PVuFgQYYnV2It7A",
      id: "1XGmzt0PVuFgQYYnV2It7A",
      is_local: false,
      name: "Payphone",
      popularity: 87,
      preview_url: null,
      track_number: 4,
      type: "track",
      uri: "spotify:track:1XGmzt0PVuFgQYYnV2It7A",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
            },
            href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
            id: "04gDigrS5kc9YWfZHwBETP",
            name: "Maroon 5",
            type: "artist",
            uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1Li4rADxSxjT2g4xqUcMYh",
        },
        href: "https://api.spotify.com/v1/albums/1Li4rADxSxjT2g4xqUcMYh",
        id: "1Li4rADxSxjT2g4xqUcMYh",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273deae7d931928fc1543e70203",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02deae7d931928fc1543e70203",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851deae7d931928fc1543e70203",
            width: 64,
          },
        ],
        name: "Red Pill Blues (Deluxe)",
        release_date: "2018-06-15",
        release_date_precision: "day",
        total_tracks: 22,
        type: "album",
        uri: "spotify:album:1Li4rADxSxjT2g4xqUcMYh",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
          },
          href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
          id: "04gDigrS5kc9YWfZHwBETP",
          name: "Maroon 5",
          type: "artist",
          uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/7tYKF4w9nC0nq9CsPZTHyP",
          },
          href: "https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP",
          id: "7tYKF4w9nC0nq9CsPZTHyP",
          name: "SZA",
          type: "artist",
          uri: "spotify:artist:7tYKF4w9nC0nq9CsPZTHyP",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 199849,
      explicit: false,
      external_ids: {
        isrc: "USUM71709292",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0GxQ1A5L9xnMOytbP6eKBG",
      },
      href: "https://api.spotify.com/v1/tracks/0GxQ1A5L9xnMOytbP6eKBG",
      id: "0GxQ1A5L9xnMOytbP6eKBG",
      is_local: false,
      name: "What Lovers Do (feat. SZA)",
      popularity: 75,
      preview_url: null,
      track_number: 2,
      type: "track",
      uri: "spotify:track:0GxQ1A5L9xnMOytbP6eKBG",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
            },
            href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
            id: "04gDigrS5kc9YWfZHwBETP",
            name: "Maroon 5",
            type: "artist",
            uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1pCA38N6MkLlthXtAOvZTU",
        },
        href: "https://api.spotify.com/v1/albums/1pCA38N6MkLlthXtAOvZTU",
        id: "1pCA38N6MkLlthXtAOvZTU",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27386a8ab515de4b7aef28cd631",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0286a8ab515de4b7aef28cd631",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485186a8ab515de4b7aef28cd631",
            width: 64,
          },
        ],
        name: "JORDI (Deluxe)",
        release_date: "2021-06-11",
        release_date_precision: "day",
        total_tracks: 14,
        type: "album",
        uri: "spotify:album:1pCA38N6MkLlthXtAOvZTU",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP",
          },
          href: "https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP",
          id: "04gDigrS5kc9YWfZHwBETP",
          name: "Maroon 5",
          type: "artist",
          uri: "spotify:artist:04gDigrS5kc9YWfZHwBETP",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/181bsRPaVXVlUKXrxwZfHK",
          },
          href: "https://api.spotify.com/v1/artists/181bsRPaVXVlUKXrxwZfHK",
          id: "181bsRPaVXVlUKXrxwZfHK",
          name: "Megan Thee Stallion",
          type: "artist",
          uri: "spotify:artist:181bsRPaVXVlUKXrxwZfHK",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 227395,
      explicit: false,
      external_ids: {
        isrc: "USUM72103449",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5zFglKYiknIxks8geR8rcL",
      },
      href: "https://api.spotify.com/v1/tracks/5zFglKYiknIxks8geR8rcL",
      id: "5zFglKYiknIxks8geR8rcL",
      is_local: false,
      name: "Beautiful Mistakes (feat. Megan Thee Stallion)",
      popularity: 87,
      preview_url: null,
      track_number: 1,
      type: "track",
      uri: "spotify:track:5zFglKYiknIxks8geR8rcL",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V",
            },
            href: "https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
            id: "6eUKZXaKkcviH0Ku9w2n3V",
            name: "Ed Sheeran",
            type: "artist",
            uri: "spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
          },
        ],
        available_markets: [
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LU",
          "LV",
          "MA",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1xn54DMo2qIqBuMqHtUsFd",
        },
        href: "https://api.spotify.com/v1/albums/1xn54DMo2qIqBuMqHtUsFd",
        id: "1xn54DMo2qIqBuMqHtUsFd",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27313b3e37318a0c247b550bccd",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0213b3e37318a0c247b550bccd",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485113b3e37318a0c247b550bccd",
            width: 64,
          },
        ],
        name: "x (Deluxe Edition)",
        release_date: "2014-06-21",
        release_date_precision: "day",
        total_tracks: 16,
        type: "album",
        uri: "spotify:album:1xn54DMo2qIqBuMqHtUsFd",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V",
          },
          href: "https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
          id: "6eUKZXaKkcviH0Ku9w2n3V",
          name: "Ed Sheeran",
          type: "artist",
          uri: "spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
        },
      ],
      available_markets: [
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LT",
        "LU",
        "LV",
        "MA",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 258986,
      explicit: false,
      external_ids: {
        isrc: "GBAHS1400094",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1HNkqx9Ahdgi1Ixy2xkKkL",
      },
      href: "https://api.spotify.com/v1/tracks/1HNkqx9Ahdgi1Ixy2xkKkL",
      id: "1HNkqx9Ahdgi1Ixy2xkKkL",
      is_local: false,
      name: "Photograph",
      popularity: 88,
      preview_url:
        "https://p.scdn.co/mp3-preview/34704823c55ae09f26988b106784f884bb781068?cid=774b29d4f13844c495f206cafdad9c86",
      track_number: 6,
      type: "track",
      uri: "spotify:track:1HNkqx9Ahdgi1Ixy2xkKkL",
    },
    {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V",
            },
            href: "https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
            id: "6eUKZXaKkcviH0Ku9w2n3V",
            name: "Ed Sheeran",
            type: "artist",
            uri: "spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3Pl0yCO51uGkr5tFlD6bWN",
        },
        href: "https://api.spotify.com/v1/albums/3Pl0yCO51uGkr5tFlD6bWN",
        id: "3Pl0yCO51uGkr5tFlD6bWN",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b775d9e0b2d6d2279a0a7373",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b775d9e0b2d6d2279a0a7373",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b775d9e0b2d6d2279a0a7373",
            width: 64,
          },
        ],
        name: "Visiting Hours",
        release_date: "2021-08-19",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3Pl0yCO51uGkr5tFlD6bWN",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V",
          },
          href: "https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
          id: "6eUKZXaKkcviH0Ku9w2n3V",
          name: "Ed Sheeran",
          type: "artist",
          uri: "spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 215506,
      explicit: false,
      external_ids: {
        isrc: "GBAHS2100680",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/44V6EzbUSYgyfsNiP0FrlA",
      },
      href: "https://api.spotify.com/v1/tracks/44V6EzbUSYgyfsNiP0FrlA",
      id: "44V6EzbUSYgyfsNiP0FrlA",
      is_local: false,
      name: "Visiting Hours",
      popularity: 78,
      preview_url:
        "https://p.scdn.co/mp3-preview/2b4f878998be450794e732f6d437346736cb8e0a?cid=774b29d4f13844c495f206cafdad9c86",
      track_number: 1,
      type: "track",
      uri: "spotify:track:44V6EzbUSYgyfsNiP0FrlA",
    },
  ],
  total: 50,
  limit: 6,
  offset: 0,
  previous: null,
  href: "https://api.spotify.com/v1/me/top/tracks?limit=6&offset=0",
  next: "https://api.spotify.com/v1/me/top/tracks?limit=6&offset=6",
};

const FeaturedPlaylists = {
  message: "Editor's picks",
  playlists: {
    href: "https://api.spotify.com/v1/browse/featured-playlists?timestamp=2022-04-03T16%3A27%3A44&offset=0&limit=6",
    items: [
      {
        collaborative: false,
        description: "Summer memories from yesteryear!",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1DWZg863fGtALu",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1DWZg863fGtALu",
        id: "37i9dQZF1DWZg863fGtALu",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67706f0000000327300e5b4c0f371be20b4fb4",
            width: null,
          },
        ],
        name: "Summer Throwbacks",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: null,
        snapshot_id:
          "MTYyMTIwNjAwMCwwMDAwMDAzNjAwMDAwMTc5Nzc2ODYxZTUwMDAwMDE3OGE3MzJhMDRl",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1DWZg863fGtALu/tracks",
          total: 80,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1DWZg863fGtALu",
      },
      {
        collaborative: false,
        description:
          "New music from Lil Tjay, A Boogie Wit da Hoodie and J. Cole's Dreamville crew. ",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX0XUsuxWHRQd",
        id: "37i9dQZF1DX0XUsuxWHRQd",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67706f00000003dfe524eda2356023764dbc53",
            width: null,
          },
        ],
        name: "RapCaviar",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: null,
        snapshot_id:
          "MTY0ODc4NTYwMCwwMDAwMDY0OTAwMDAwMTdmZTM0N2FlYTMwMDAwMDE3ZmRiZTNmZDc4",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX0XUsuxWHRQd/tracks",
          total: 50,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1DX0XUsuxWHRQd",
      },
      {
        collaborative: false,
        description: "All the jams. Cover: Usher",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1DWXnexX7CktaI",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1DWXnexX7CktaI",
        id: "37i9dQZF1DWXnexX7CktaI",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67706f00000003e43cedef4710a3a3d391c68d",
            width: null,
          },
        ],
        name: "Gold Edition",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: null,
        snapshot_id:
          "MTY0OTAwMzI2MSwwMDAwMDAwMGQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0Mjdl",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1DWXnexX7CktaI/tracks",
          total: 40,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1DWXnexX7CktaI",
      },
      {
        collaborative: false,
        description:
          "Songs from the 90s that made you sing and dance all summer long",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1DX8SIpKv9qw6x",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX8SIpKv9qw6x",
        id: "37i9dQZF1DX8SIpKv9qw6x",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67706f00000003b8c66d3b26fe38c2bc1ce8fa",
            width: null,
          },
        ],
        name: "Summer Hits of the 90s",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: null,
        snapshot_id:
          "MTY0OTAwMzIyMCwwMDAwMDAwMGQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0Mjdl",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX8SIpKv9qw6x/tracks",
          total: 80,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1DX8SIpKv9qw6x",
      },
      {
        collaborative: false,
        description: "Embrace your secret favorites.",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1DX4pUKG1kS0Ac",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX4pUKG1kS0Ac",
        id: "37i9dQZF1DX4pUKG1kS0Ac",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67706f000000034a2afca194d4819c57201bc3",
            width: null,
          },
        ],
        name: "Guilty Pleasures",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: null,
        snapshot_id:
          "MTY0OTAwMzIwNCwwMDAwMDAwMGQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0Mjdl",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX4pUKG1kS0Ac/tracks",
          total: 150,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1DX4pUKG1kS0Ac",
      },
      {
        collaborative: false,
        description: "Khalid is celebrating 5 years of American Teen.",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1DX5Ejj0EkURtP",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX5Ejj0EkURtP",
        id: "37i9dQZF1DX5Ejj0EkURtP",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67706f00000003db418d45f34cc1e21979dc88",
            width: null,
          },
        ],
        name: "All Out 2010s",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: null,
        snapshot_id:
          "MTY0OTAwMzI2NCwwMDAwMDAwMGQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0Mjdl",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX5Ejj0EkURtP/tracks",
          total: 150,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1DX5Ejj0EkURtP",
      },
    ],
    limit: 6,
    next: "https://api.spotify.com/v1/browse/featured-playlists?timestamp=2022-04-03T16%3A27%3A44&offset=6&limit=6",
    offset: 0,
    previous: null,
    total: 11,
  },
};

const NewReleases = {
  albums: {
    href: "https://api.spotify.com/v1/browse/new-releases?locale=en-US%2Cen%3Bq%3D0.9&offset=0&limit=6",
    items: [
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3",
            },
            href: "https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3",
            id: "6KImCVD70vtIoJWnq6nGn3",
            name: "Harry Styles",
            type: "artist",
            uri: "spotify:artist:6KImCVD70vtIoJWnq6nGn3",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2pqdSWeJVsXAhHFuVLzuA8",
        },
        href: "https://api.spotify.com/v1/albums/2pqdSWeJVsXAhHFuVLzuA8",
        id: "2pqdSWeJVsXAhHFuVLzuA8",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b46f74097655d7f353caab14",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b46f74097655d7f353caab14",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b46f74097655d7f353caab14",
            width: 64,
          },
        ],
        name: "As It Was",
        release_date: "2022-03-31",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:2pqdSWeJVsXAhHFuVLzuA8",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7n2wHs1TKAczGzO7Dd2rGr",
            },
            href: "https://api.spotify.com/v1/artists/7n2wHs1TKAczGzO7Dd2rGr",
            id: "7n2wHs1TKAczGzO7Dd2rGr",
            name: "Shawn Mendes",
            type: "artist",
            uri: "spotify:artist:7n2wHs1TKAczGzO7Dd2rGr",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4EGVr9mSwFPoqvDMkiahJp",
        },
        href: "https://api.spotify.com/v1/albums/4EGVr9mSwFPoqvDMkiahJp",
        id: "4EGVr9mSwFPoqvDMkiahJp",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273dad0775943c1a826bfed3117",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02dad0775943c1a826bfed3117",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851dad0775943c1a826bfed3117",
            width: 64,
          },
        ],
        name: "When You're Gone",
        release_date: "2022-03-31",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:4EGVr9mSwFPoqvDMkiahJp",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5",
            },
            href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
            id: "0L8ExT028jH3ddEcZwqJJ5",
            name: "Red Hot Chili Peppers",
            type: "artist",
            uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2ITVvrNiINKRiW7wA3w6w6",
        },
        href: "https://api.spotify.com/v1/albums/2ITVvrNiINKRiW7wA3w6w6",
        id: "2ITVvrNiINKRiW7wA3w6w6",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27397a52e0aeda9d95fb881c56d",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0297a52e0aeda9d95fb881c56d",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485197a52e0aeda9d95fb881c56d",
            width: 64,
          },
        ],
        name: "Unlimited Love",
        release_date: "2022-04-01",
        release_date_precision: "day",
        total_tracks: 17,
        type: "album",
        uri: "spotify:album:2ITVvrNiINKRiW7wA3w6w6",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7HkdQ0gt53LP4zmHsL0nap",
            },
            href: "https://api.spotify.com/v1/artists/7HkdQ0gt53LP4zmHsL0nap",
            id: "7HkdQ0gt53LP4zmHsL0nap",
            name: "Ella Mai",
            type: "artist",
            uri: "spotify:artist:7HkdQ0gt53LP4zmHsL0nap",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2kiSvbyjIZCsoSYw40josY",
        },
        href: "https://api.spotify.com/v1/albums/2kiSvbyjIZCsoSYw40josY",
        id: "2kiSvbyjIZCsoSYw40josY",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2739af92b0ea5e0d6859ee46b0a",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e029af92b0ea5e0d6859ee46b0a",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048519af92b0ea5e0d6859ee46b0a",
            width: 64,
          },
        ],
        name: "Leave You Alone",
        release_date: "2022-03-31",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:2kiSvbyjIZCsoSYw40josY",
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6x2LnllRG5uGarZMsD4iO8",
            },
            href: "https://api.spotify.com/v1/artists/6x2LnllRG5uGarZMsD4iO8",
            id: "6x2LnllRG5uGarZMsD4iO8",
            name: "Thomas Rhett",
            type: "artist",
            uri: "spotify:artist:6x2LnllRG5uGarZMsD4iO8",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/794M3R461sLnY042CsB3xW",
        },
        href: "https://api.spotify.com/v1/albums/794M3R461sLnY042CsB3xW",
        id: "794M3R461sLnY042CsB3xW",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273809f7252c726950e7e38963b",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02809f7252c726950e7e38963b",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851809f7252c726950e7e38963b",
            width: 64,
          },
        ],
        name: "Where We Started",
        release_date: "2022-04-01",
        release_date_precision: "day",
        total_tracks: 15,
        type: "album",
        uri: "spotify:album:794M3R461sLnY042CsB3xW",
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6jGMq4yGs7aQzuGsMgVgZR",
            },
            href: "https://api.spotify.com/v1/artists/6jGMq4yGs7aQzuGsMgVgZR",
            id: "6jGMq4yGs7aQzuGsMgVgZR",
            name: "Lil Tjay",
            type: "artist",
            uri: "spotify:artist:6jGMq4yGs7aQzuGsMgVgZR",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5pK7kqzGXSY7xoLMhfHlql",
        },
        href: "https://api.spotify.com/v1/albums/5pK7kqzGXSY7xoLMhfHlql",
        id: "5pK7kqzGXSY7xoLMhfHlql",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2731e6a9d4ce04b67a455ed6b8c",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e021e6a9d4ce04b67a455ed6b8c",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048511e6a9d4ce04b67a455ed6b8c",
            width: 64,
          },
        ],
        name: "In My Head",
        release_date: "2022-04-01",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:5pK7kqzGXSY7xoLMhfHlql",
      },
    ],
    limit: 6,
    next: "https://api.spotify.com/v1/browse/new-releases?locale=en-US%2Cen%3Bq%3D0.9&offset=6&limit=6",
    offset: 0,
    previous: null,
    total: 100,
  },
};

function generateCard(image, name, description, href) {
  return `
    <a class="card" href="${href}" target="_blank">
        <img
            src="${image}"
            alt="peaceful piano"
            srcset=""
        />
        <span class="mdi mdi-play mdi-36px"></span>
        <div class="title">${name}</div>
        <div class="subtitle">${description}</div>
    </a>
    `;
}

// Mapping UserTopItems - Start
const sectionTopItems = document.querySelector("#your-top-items");
const sectionTopItemsTitle = sectionTopItems.querySelector(".title");
const sectionTopItemsSubtitle = sectionTopItems.querySelector(".subtitle");
const sectionTopItemsWrapper = sectionTopItems.querySelector(".card-wrapper");
sectionTopItemsTitle.textContent = "Your Top Items";
sectionTopItemsSubtitle.textContent = "Based on your recent listening";
for (let i = 0; i < UserTopItems.items.length; i++) {
  const track = UserTopItems.items[i];

  const image = track.album.images[1].url;
  const name = track.name;
  const description = track.album.artists
    .map((artist) => artist.name)
    .join(", ");
  const href = track.album.external_urls.spotify;

  sectionTopItemsWrapper.innerHTML += generateCard(
    image,
    name,
    description,
    href
  );
}
// Mapping UserTopItems - End

// Mapping FeaturedPlaylists - Start
const sectionFeaturedPlaylists = document.querySelector("#featured-playlists");
const sectionFeaturedPlaylistsTitle =
  sectionFeaturedPlaylists.querySelector(".title");
const sectionFeaturedPlaylistsSubtitle =
  sectionFeaturedPlaylists.querySelector(".subtitle");
const sectionFeaturedPlaylistsWrapper =
  sectionFeaturedPlaylists.querySelector(".card-wrapper");
sectionFeaturedPlaylistsTitle.textContent = FeaturedPlaylists.message;
sectionFeaturedPlaylistsSubtitle.textContent = "";
for (let i = 0; i < FeaturedPlaylists.playlists.items.length; i++) {
  const track = FeaturedPlaylists.playlists.items[i];

  const image = track.images[0].url;
  const name = track.name;
  const description = track.description;
  const href = track.external_urls.spotify;

  sectionFeaturedPlaylistsWrapper.innerHTML += generateCard(
    image,
    name,
    description,
    href
  );
}
// Mapping FeaturedPlaylists - End

// Mapping NewReleases - Start
const sectionNewReleases = document.querySelector("#new-releases");
const sectionNewReleasesTitle = sectionNewReleases.querySelector(".title");
const sectionNewReleasesSubtitle =
  sectionNewReleases.querySelector(".subtitle");
const sectionNewReleasesWrapper =
  sectionNewReleases.querySelector(".card-wrapper");
sectionNewReleasesTitle.textContent = "Popular New Releases";
sectionNewReleasesSubtitle.textContent = "";
for (let i = 0; i < NewReleases.albums.items.length; i++) {
  const track = NewReleases.albums.items[i];

  const image = track.images[1].url;
  const name = track.name;
  const description = track.artists.map((artist) => artist.name).join(", ");
  const href = track.external_urls.spotify;

  sectionNewReleasesWrapper.innerHTML += generateCard(
    image,
    name,
    description,
    href
  );
}
// Mapping NewReleases - End
